### ISSUE TITLE
Support for additional file formats.

### ISSUE THREAD

**Issue by Wastelander121** [Wastelander121/TFCToolsIssueTracker#53]
Some games, such as Mortal Kombat and Injustice use .xxx in place of .upk. 

Games affected:
Deadpool #15 
Injustice #22 
Injustice 2 #23 
Mortal Kombat Komplete Edition #27  
Mortal Kombat X #28 
Transformers: Fall of Cybertron #41
Transformers: Rise of the Dark Spark #42
Transformers: War of Cybertron #43
X-Men Origins: Wolverine #51

**Comment by FCH823** [comment]
I've added support for it. You will have it with the next version when it's ready

**Comment by FCH823** [comment]
Added .xxx in v1.2
Also from now on it's possible to add upk extensions directly in PackageExtensions.xml

**Comment by Wastelander121** [comment]
Fixed as of 1.2 :)
