### ISSUE TITLE
Incompatibility with some games that don't store the UPK in the same folder as the TFCs

### ISSUE THREAD

**Issue by Wastelander121** [Wastelander121/TFCToolsIssueTracker#57]
TFC Tools are currently only compatible with a game that's directory stores everything in this path:

"ExampleGame\CookedPCConsole"

Some games have multiple subfolders, where the tfc isn't stored in the same folder, for example:

Our UPK is stored here: "Hunted\DFGAME\COOKEDPC\MAPS\CHAPTER1\01_ENTERTOWN" it is looking for Textures.tfc 
Textures.tfc is stored here: "Hunted\DFGAME\COOKEDPC"

In order to correct this problem, the TFC Tools' explorer needs to be able to read all subfolders passed "CookedPC" or "CookedPCConsole". 

The Open UPK Folder option should work as intended, but also needs to scan all subdirectories.

Games affected:
Fabe Anniversary #18 
Hunted: The Demon's Forge #21

**Comment by FCH823** [comment]
This should also be fixed once folder structure support is implemented

**Comment by FCH823** [comment]
This will need retesting with version 1.2 as it is now possible to create a game profile with tfc folder path different than package folder path

**Comment by Wastelander121** [comment]
Fixed in 1.2, so long as a game profile is created per game to account for it.
