### ISSUE TITLE
No '.TFCMapping' file found in selected folder

### ISSUE THREAD

**Issue by Wastelander121** [Wastelander121/TFCToolsIssueTracker#59]
No '.TFCMapping' file found in selected folder error occurs despite the file being present. Prevents in-depth testing of games which may be compatible. Affected games:

Abyss Odyssey #63 
Adam's Venture #64
Aliens: Colonial Marines #1 
Brothers: A Tale of Two Sons #65
Deadfall Adventures #66
Flashback  #68
GET EVEN #69 (nice)
Goat Simulator #58
Hunted: The Demon's Forge #21
Killing Floor 2 #25 
Life is Strange #72
MIND Path to Thalamus #73
Painkiller: Pain and Damnation #74
Rise of the Triad #75
Sanctum #76
Sanctum 2 #77
Spec Ops: The Line #37 
Styx: Master of Shadows #38   
Tony Hawk: Pro Skater HD #40 
Outlast #31 
XCom: Declassified #50 
XCom: Enemy Unknown #48 
Zeno Clash 2 #78

**Comment by FCH823** [comment]
This will be fixed once i've implemented folder structure support.
That's because the name of the TFCMapping files are hardcoded and based on what game (dishonored) or DLC (dishonored DLC) is detected. So when the folder structure doesn't match dishonored, you get a null name and then this error...

**Comment by FCH823** [comment]
This should definitely be fixed with 1.2 as TFC mapping names are now defined in game profile xml files

**Comment by Wastelander121** [comment]
Confirmed fixed in 1.2.
