### ISSUE TITLE
Support for when multiple games use the same Package and License versions.

### ISSUE THREAD

**Issue by Wastelander121** [Wastelander121/TFCToolsIssueTracker#87]
When games that share Package and License versions are loaded, the Explorer will give an error: 
![image](https://user-images.githubusercontent.com/29731570/226600308-1cc79cb8-81fe-4515-a486-7f41414928eb.png)

Games affected:
Borderlands 2 and Borderlands: The Pre-Sequel
Painkiller: Hell and Damnation and Flashback (2013)

Workaround: Only store the profile of the game you're modding at the time in GameProfiles.

**Comment by FCH823** [comment]
Should be fixed with v1.2.1.0
